<?php
defined('MOODLE_INTERNAL') || die();

$functions = [
    'rucksack_get_all_badges' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'get_all_badges',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Get all enabled badges',
        'type'          => 'read',
        'capabilities'  => 'moodle/badges:viewbadges',
        'ajax'          => true,
    ],
    'rucksack_get_user_badge_awards' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'get_user_badge_awards',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Get all users with their badge awards',
        'type'          => 'read',
        'capabilities'  => 'moodle/badges:viewbadges',
        'ajax'          => true,
    ],
    'rucksack_create_config_set' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'create_config_set',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Create a new badge configuration set',
        'type'          => 'write',
        'capabilities'  => 'local/rucksack:manageconfigs',
        'ajax'          => true,
    ],
    'rucksack_update_config_set' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'update_config_set',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Update a badge configuration set',
        'type'          => 'write',
        'capabilities'  => 'local/rucksack:manageconfigs',
        'ajax'          => true,
    ],
    'rucksack_delete_config_set' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'delete_config_set',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Delete a badge configuration set',
        'type'          => 'write',
        'capabilities'  => 'local/rucksack:manageconfigs',
        'ajax'          => true,
    ],
    'rucksack_get_config_sets' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'get_config_sets',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'List all badge configuration sets',
        'type'          => 'read',
        'capabilities'  => 'local/rucksack:manageconfigs',
        'ajax'          => true,
    ],
    'rucksack_get_config_set' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'get_config_set',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Get a single badge configuration set',
        'type'          => 'read',
        'capabilities'  => 'local/rucksack:manageconfigs',
        'ajax'          => true,
    ],
    'rucksack_assign_config_set' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'assign_config_set',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Assign a configuration set to users',
        'type'          => 'write',
        'capabilities'  => 'local/rucksack:manageconfigs',
        'ajax'          => true,
    ],
    'rucksack_unassign_config_set' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'unassign_config_set',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Unassign a configuration set from users',
        'type'          => 'write',
        'capabilities'  => 'local/rucksack:manageconfigs',
        'ajax'          => true,
    ],
    'rucksack_get_user_config_set' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'get_user_config_set',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Get the configuration set assigned to a user',
        'type'          => 'read',
        'capabilities'  => 'local/rucksack:manageconfigs',
        'ajax'          => true,
    ],
    'rucksack_get_earned_badges' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'get_earned_badges',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Get earned badges for a user as JSON data',
        'type'          => 'read',
        'capabilities'  => '',
        'ajax'          => true,
        'loginrequired' => false,
    ],
    'rucksack_get_earned_badges_html' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'get_earned_badges_html',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Get rendered earned badges HTML for a user',
        'type'          => 'read',
        'capabilities'  => '',
        'ajax'          => true,
        'loginrequired' => false,
    ],
    'rucksack_get_earned_badges_pdf_url' => [
        'classname'     => 'local_rucksack_external',
        'methodname'    => 'get_earned_badges_pdf_url',
        'classpath'     => 'local/rucksack/externallib.php',
        'description'   => 'Get the public PDF URL for a user',
        'type'          => 'read',
        'capabilities'  => 'local/rucksack:manageconfigs',
        'ajax'          => true,
    ],
];

$services = [
    'Rucksack Service' => [
        'functions' => [
            'rucksack_get_all_badges',
            'rucksack_get_user_badge_awards',
            'rucksack_create_config_set',
            'rucksack_update_config_set',
            'rucksack_delete_config_set',
            'rucksack_get_config_sets',
            'rucksack_get_config_set',
            'rucksack_assign_config_set',
            'rucksack_unassign_config_set',
            'rucksack_get_user_config_set',
            'rucksack_get_earned_badges',
            'rucksack_get_earned_badges_html',
            'rucksack_get_earned_badges_pdf_url',
        ],
        'restrictedusers' => 0,
        'enabled' => 1,
    ],
];
