<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit572e15b9d2a9d190ca9c9299385d3c03
{
    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'chillerlan\\Settings\\' => 20,
            'chillerlan\\QRCode\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'chillerlan\\Settings\\' => 
        array (
            0 => __DIR__ . '/..' . '/chillerlan/php-settings-container/src',
        ),
        'chillerlan\\QRCode\\' => 
        array (
            0 => __DIR__ . '/..' . '/chillerlan/php-qrcode/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit572e15b9d2a9d190ca9c9299385d3c03::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit572e15b9d2a9d190ca9c9299385d3c03::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit572e15b9d2a9d190ca9c9299385d3c03::$classMap;

        }, null, ClassLoader::class);
    }
}
